name: GitHub Actions Demo
on: [push]
jobs:
  run-python-code:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ the job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß this job is now running on a ${{ runner.os }} server hosted by github!"
      - run: echo "üîé the name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: check out repository code
        uses: actions/checkout@v2
      - run: echo "üí° the ${{ github.repository }} repository has been cloned to the runner."
      - name: checkout gitbook repo
        uses: actions/checkout@v2
        with:
          repository: wandb/gitbook
          path: documentation
          ref: en
      - name: checkout docugen repo
        uses: actions/checkout@v2
        with:
          repository: wandb/docugen
          path: documentation
      - run: echo "üñ•Ô∏è the workflow is now ready to test your code on the runner."
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: setup python environment
        working-directory: ./documentation/docugen
        run: python -m pip install -r requirements.txt
      - run: python -c 'import sys; print(sys.path)'
      - run: echo üêç $PYTHONPATH
      - name: check for docugen
        working-directory: ./documentation/docugen
        run: python -c 'import docugen'
      - name: generate documentation
        working-directory: ./documentation/docugen
      - run: python generate.py --template_file ../gitbook/SUMMARY.md --commit_id v0.12.5 --output_dir ../gitbook
      - run: cat ./documentation/gitbook/SUMMARY.MD
      - name: exit
        run: echo "üçè this job's status is ${{ job.status }}."
