name: GitHub Actions Demo
on: [push]
jobs:
  run-python-code:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ the job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ this job is now running on a ${{ runner.os }} server hosted by github!"
      - run: echo "ğŸ” the name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ the ${{ github.repository }} repository has been cloned to the runner."
      - name: checkout docugen repo
        uses: actions/checkout@v2
        with:
          repository: wandb/gitbook
          path: documentation
          ref: en
      - run: echo "ğŸ–¥ï¸ the workflow is now ready to test your code on the runner."
      - name: setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: python -m pip install -r requirements.txt
      - run: python -c 'print("hello world!")'
      - name: exit
        run: echo "ğŸ this job's status is ${{ job.status }}."
