name: Generation Documentation
on: [push]
jobs:
  run-documentation-generator:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ the job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ this job is now running on a ${{ runner.os }} server hosted by github!"
      - run: echo "ğŸ” the name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ the ${{ github.repository }} repository has been cloned to the runner."
      - name: checkout gitbook repo
        uses: actions/checkout@v2
        with:
          repository: wandb/gitbook
          path: documentation/gitbook
          ref: en
      - name: checkout docugen repo
        uses: actions/checkout@v2
        with:
          repository: wandb/docugen
          path: documentation/docugen
      - run: echo "ğŸ–¥ï¸ the workflow is now ready to test your code on the runner."
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: setup python environment
        run: python -m pip install -r ./documentation/docugen/requirements.txt
      - name: generate documentation
        working-directory: ./documentation/docugen
        run: python generate.py --template_file ../gitbook/SUMMARY.md --commit_id v0.12.5 --output_dir ../gitbook
      - run: cat ./documentation/gitbook/SUMMARY.md
      - run: cat ./documentation/gitbook/
      - name: exit
        run: echo "ğŸ this job's status is ${{ job.status }}."
